#!/bin/bash
echo 'http ALL=(ALL) NOPASSWD: ALL' | sudo tee -a /etc/sudoers
usermod -a -G audio http

if [ -d "/opt/logitechmediaserver-git/cache/InstalledPlugins/Plugins/MaterialSkin" ]; then
cd /tmp
# wget https://raw.githubusercontent.com/lovehifi/addraudio/main/configui.tar.gz
wget https://raw.githubusercontent.com/lovehifi/addraudio/main/configgui2.tar.gz
wget https://raw.githubusercontent.com/lovehifi/addraudio/main/actionmenu.tar.gz
#tar -xzvf configui.tar.gz --overwrite -C /
tar -xzvf configgui2.tar.gz --overwrite -C /
tar -xzvf actionmenu.tar.gz --overwrite -C /

chown logitechms:logitechms -Rv /opt/logitechmediaserver-git/prefs/material-skin
chown http:http /etc/asound.conf
chown http:http -Rv /srv/http/config

hostname=$(hostname)
replacement="http://${hostname}"
if [ -f "/srv/http/assets/js/main.js" ]; then
sed -i "s|https://github.com/rern/rAudio/discussions|${replacement}:9000|g" /srv/http/assets/js/main.js
echo "Completed."
else
echo "Skipping..."
fi
echo "Install Finished, please reboot"

else
    echo "Please install Material Skin before installing this script"
fi
