#!/bin/bash
echo "hostname.ddns.net" | sudo tee /boot/ip.ini
cd /tmp
wget https://raw.githubusercontent.com/lovehifi/addraudio/main/getip.sh
wget https://raw.githubusercontent.com/lovehifi/addraudio/main/connectnfs.service

chmod -R 755 /tmp/getip.sh
cp -f /tmp/getip.sh /opt/

chmod -R 755 /tmp/connectnfs.service
cp -f /tmp/connectnfs.service /etc/systemd/system/

systemctl daemon-reload
systemctl enable connectnfs.service
systemctl restart connectnfs.service

echo "Finished, Change your web in file /boot/ip.ini and reboot"
#systemctl status connectnfs.service

